import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { CategoryProvider } from '@/context/CategoryContext'
import './globals.css'
import Navbar from '@/common/componants/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='mx-36 text-2xl'>
          <Navbar></Navbar>
          <div className='flex flex-col items-center text-center mt-32'>
            <CategoryProvider>
              {children}
            </CategoryProvider>
          </div>
        </div>
      </body>
    </html>
  )
}
